/*******************************************/
/*     FILE GENERATED BY iec2c             */
/* Editing this file is not recommended... */
/*******************************************/

#include "iec_std_lib.h"

#include "accessor.h"

#include "POUS.h"

// CONFIGURATION CFF

void SDS_init__(void);

void config_init__(void) {
  BOOL retain;
  retain = 0;
  
  SDS_init__();
}

void SDS_run__(unsigned long tick);

void config_run__(unsigned long tick) {
  SDS_run__(tick);
}
unsigned long long common_ticktime__ = 1000000ULL; /*ns*/
unsigned long greatest_tick_count__ = 0UL; /*tick*/
