
/* File generated by gen_cfile.py. Should not be modified. */

#include "OD_0_0.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 OD_0_0_trashvariables_TRASH1 = 0x0;		/* Mapped at index 0x2000, subindex 0x01 */
UNS8 OD_0_0_trashvariables_TRASH8 = 0x0;		/* Mapped at index 0x2000, subindex 0x02 */
UNS16 OD_0_0_trashvariables_TRASH16 = 0x0;		/* Mapped at index 0x2000, subindex 0x03 */
UNS32 OD_0_0_trashvariables_TRASH32 = 0x0;		/* Mapped at index 0x2000, subindex 0x04 */
UNS64 OD_0_0_trashvariables_TRASH64 = 0x0;		/* Mapped at index 0x2000, subindex 0x05 */
UNS8 beremiz__IB0_0_8_24576_1 = 0x0;		/* Mapped at index 0x2208, subindex 0x01 */
UNS8 Can_Bitrate = 0x6;		/* Mapped at index 0x4000, subindex 0x00 */
UNS8 SYS_TICK_PERIOD_MS = 0x8;		/* Mapped at index 0x4001, subindex 0x00 */
UNS8 Axis_Number = 0x8;		/* Mapped at index 0x4002, subindex 0x00 */
UNS8 Axis_Types[] =		/* Mapped at index 0x4003, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x2,	/* 2 */
    0x0	/* 0 */
  };
UNS8 Axis_Mods[] =		/* Mapped at index 0x4004, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
INTEGER8 Homing_methods[] =		/* Mapped at index 0x4005, subindex 0x01 - 0x04 */
  {
    0x1,	/* 1 */
    0x1,	/* 1 */
    0x1,	/* 1 */
    0x1	/* 1 */
  };
UNS32 Homing_Speeds_during_search_for_switch[] =		/* Mapped at index 0x4006, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS32 Homing_Speeds_during_search_for_zero[] =		/* Mapped at index 0x4007, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS32 Homing_Accelerations[] =		/* Mapped at index 0x4008, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
INTEGER32 Homing_Position_offset[] =		/* Mapped at index 0x4009, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS8 CAM_0[] =		/* Mapped at index 0x400A, subindex 0x01 - 0x0A */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS8 CAM_1[] =		/* Mapped at index 0x400B, subindex 0x01 - 0x0A */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS16 Interpolation_data_records_low[] =		/* Mapped at index 0x4010, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS16 Interpolation_data_records_high[] =		/* Mapped at index 0x4011, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS16 ControlWords[] =		/* Mapped at index 0x4012, subindex 0x01 - 0x04 */
  {
    0x1F,	/* 31 */
    0x1F,	/* 31 */
    0x1F,	/* 31 */
    0x1F	/* 31 */
  };
UNS32 Max_accelerations[] =		/* Mapped at index 0x4020, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS32 Max_Decelerations[] =		/* Mapped at index 0x4021, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS32 Max_Velocitys[] =		/* Mapped at index 0x4022, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS32 Position_Factor_Numerators[] =		/* Mapped at index 0x4030, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x80	/* 128 */
  };
UNS32 Position_Factor_Feed_Constants[] =		/* Mapped at index 0x4031, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x1	/* 1 */
  };
UNS32 Pulse_Per_Rotate[] =		/* Mapped at index 0x4032, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS32 interrupt_register[] =		/* Mapped at index 0x4033, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS8 finish_flag_register[] =		/* Mapped at index 0x4034, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS8 Execute_flag_register[] =		/* Mapped at index 0x4035, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS8 command_to_request_type[] =		/* Mapped at index 0x4036, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
REAL32 Pulse_Equivalent[] =		/* Mapped at index 0x4037, subindex 0x01 - 0x04 */
  {
    0.000000,
    0.000000,
    0.000000,
    0.000100
  };
UNS32 Soft_Limits_Low[] =		/* Mapped at index 0x4040, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS32 Soft_Limits_High[] =		/* Mapped at index 0x4041, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS8 Gear_Inputs[] =		/* Mapped at index 0x4050, subindex 0x01 - 0x04 */
  {
    0x1,	/* 1 */
    0x1,	/* 1 */
    0x1,	/* 1 */
    0x1	/* 1 */
  };
UNS8 Gear_Outputs[] =		/* Mapped at index 0x4051, subindex 0x01 - 0x04 */
  {
    0x1,	/* 1 */
    0x1,	/* 1 */
    0x1,	/* 1 */
    0x1	/* 1 */
  };
UNS32 Gear_Leads[] =		/* Mapped at index 0x4053, subindex 0x01 - 0x04 */
  {
    0x1,	/* 1 */
    0x1,	/* 1 */
    0x1,	/* 1 */
    0x1	/* 1 */
  };
UNS8 Modbus_Bitrate = 0x6;		/* Mapped at index 0x4100, subindex 0x00 */
UNS8 Modbus_RTU_or_ASCII = 0x0;		/* Mapped at index 0x4101, subindex 0x00 */
UNS8 Modbus_Slave_Id = 0x0;		/* Mapped at index 0x4102, subindex 0x00 */
UNS8 Modbus_Parity = 0x0;		/* Mapped at index 0x4103, subindex 0x00 */
UNS16 Modbus_Coils[] =		/* Mapped at index 0x4110, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS16 Modbus_Holdings[] =		/* Mapped at index 0x4111, subindex 0x01 - 0x64 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS8 Debug_COM_Port_Birtrate = 0x0;		/* Mapped at index 0x4120, subindex 0x00 */
UNS8 Leds[] =		/* Mapped at index 0x4200, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS8 Keys[] =		/* Mapped at index 0x4201, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS8 beremiz__QB0_0_8_25088_1 = 0x0;		/* Mapped at index 0x4208, subindex 0x01 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 OD_0_0_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 OD_0_0_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 OD_0_0_iam_a_slave = 0;

TIMER_HANDLE OD_0_0_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 OD_0_0_obj1000 = 0x0;	/* 0 */
                    subindex OD_0_0_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&OD_0_0_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 OD_0_0_obj1001 = 0x0;	/* 0 */
                    subindex OD_0_0_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 OD_0_0_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 OD_0_0_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t OD_0_0_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex OD_0_0_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&OD_0_0_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 OD_0_0_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 OD_0_0_obj1006 = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 OD_0_0_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 OD_0_0_highestSubIndex_obj1016 = 0;
                    UNS32 OD_0_0_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 OD_0_0_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 OD_0_0_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 OD_0_0_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 OD_0_0_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 OD_0_0_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 OD_0_0_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex OD_0_0_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&OD_0_0_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&OD_0_0_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&OD_0_0_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&OD_0_0_obj1018_Serial_Number }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 OD_0_0_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 OD_0_0_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x608;	/* 1544 */
                    UNS32 OD_0_0_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x588;	/* 1416 */
                    UNS8 OD_0_0_obj1280_Node_ID_of_the_SDO_Server = 0x8;	/* 8 */
                    subindex OD_0_0_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&OD_0_0_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&OD_0_0_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&OD_0_0_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 OD_0_0_highestSubIndex_obj1400 = 5; /* number of subindex - 1*/
                    UNS32 OD_0_0_obj1400_COB_ID_used_by_PDO = 0x188;	/* 392 */
                    UNS8 OD_0_0_obj1400_Transmission_Type = 0x1;	/* 1 */
                    UNS16 OD_0_0_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 OD_0_0_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 OD_0_0_obj1400_Event_Timer = 0x0;	/* 0 */
                    subindex OD_0_0_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&OD_0_0_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&OD_0_0_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&OD_0_0_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&OD_0_0_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&OD_0_0_obj1400_Event_Timer }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 OD_0_0_highestSubIndex_obj1600 = 1; /* number of subindex - 1*/
                    UNS32 OD_0_0_obj1600[] = 
                    {
                      0x22080108	/* 570949896 */
                    };
                    subindex OD_0_0_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&OD_0_0_obj1600[0] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 OD_0_0_highestSubIndex_obj1800 = 5; /* number of subindex - 1*/
                    UNS32 OD_0_0_obj1800_COB_ID_used_by_PDO = 0x208;	/* 520 */
                    UNS8 OD_0_0_obj1800_Transmission_Type = 0x1;	/* 1 */
                    UNS16 OD_0_0_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 OD_0_0_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 OD_0_0_obj1800_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t OD_0_0_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex OD_0_0_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&OD_0_0_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&OD_0_0_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&OD_0_0_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&OD_0_0_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&OD_0_0_obj1800_Event_Timer }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 OD_0_0_highestSubIndex_obj1A00 = 1; /* number of subindex - 1*/
                    UNS32 OD_0_0_obj1A00[] = 
                    {
                      0x42080108	/* 1107820808 */
                    };
                    subindex OD_0_0_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&OD_0_0_obj1A00[0] }
                     };

/* index 0x1F22 :   Concise DCF. */
                    UNS8 OD_0_0_highestSubIndex_obj1F22 = 127; /* number of subindex - 1*/
                    INTEGER8* OD_0_0_obj1F22[] = 
                    {
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "\x18\x00\x00\x00\x60\x60\x00\x01\x00\x00\x00\x07\xc0\x60\x00\x02\x00\x00\x00\xfe\xff\x06\x10\x00\x04\x00\x00\x00\xa0\x0f\x00\x00\x00\x14\x01\x04\x00\x00\x00\x03\x02\x00\x80\x00\x14\x02\x01\x00\x00\x00\x01\x00\x16\x00\x01\x00\x00\x00\x00\x00\x16\x01\x04\x00\x00\x00\x10\x01\xc1\x60\x00\x16\x02\x04\x00\x00\x00\x10\x02\xc1\x60\x00\x16\x03\x04\x00\x00\x00\x10\x00\x40\x60\x00\x16\x00\x01\x00\x00\x00\x03\x00\x14\x01\x04\x00\x00\x00\x03\x02\x00\x00\x00\x18\x01\x04\x00\x00\x00\x83\x01\x00\x80\x00\x18\x02\x01\x00\x00\x00\x01\x00\x1a\x00\x01\x00\x00\x00\x00\x00\x1a\x01\x04\x00\x00\x00\x20\x00\x64\x60\x00\x1a\x02\x04\x00\x00\x00\x10\x00\x41\x60\x00\x1a\x00\x01\x00\x00\x00\x02\x00\x18\x01\x04\x00\x00\x00\x83\x01\x00\x00\x40\x60\x00\x02\x00\x00\x00\x06\x00\x40\x60\x00\x02\x00\x00\x00\x0f\x00",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      ""
                    };
                    subindex OD_0_0_Index1F22[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj1F22 },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[0] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[1] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[2] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[3] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[4] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[5] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[6] },
                       { RW, domain, 197, (void*)&OD_0_0_obj1F22[7] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[8] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[9] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[10] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[11] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[12] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[13] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[14] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[15] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[16] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[17] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[18] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[19] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[20] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[21] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[22] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[23] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[24] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[25] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[26] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[27] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[28] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[29] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[30] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[31] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[32] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[33] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[34] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[35] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[36] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[37] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[38] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[39] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[40] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[41] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[42] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[43] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[44] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[45] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[46] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[47] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[48] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[49] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[50] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[51] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[52] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[53] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[54] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[55] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[56] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[57] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[58] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[59] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[60] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[61] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[62] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[63] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[64] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[65] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[66] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[67] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[68] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[69] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[70] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[71] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[72] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[73] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[74] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[75] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[76] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[77] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[78] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[79] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[80] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[81] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[82] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[83] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[84] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[85] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[86] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[87] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[88] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[89] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[90] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[91] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[92] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[93] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[94] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[95] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[96] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[97] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[98] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[99] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[100] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[101] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[102] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[103] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[104] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[105] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[106] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[107] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[108] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[109] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[110] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[111] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[112] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[113] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[114] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[115] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[116] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[117] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[118] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[119] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[120] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[121] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[122] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[123] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[124] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[125] },
                       { RW, domain, 0, (void*)&OD_0_0_obj1F22[126] }
                     };

/* index 0x2000 :   Mapped variable OD_0_0_trashvariables */
                    UNS8 OD_0_0_highestSubIndex_obj2000 = 5; /* number of subindex - 1*/
                    subindex OD_0_0_Index2000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj2000 },
                       { RW, boolean, sizeof (UNS8), (void*)&OD_0_0_trashvariables_TRASH1 },
                       { RW, uint8, sizeof (UNS8), (void*)&OD_0_0_trashvariables_TRASH8 },
                       { RW, uint16, sizeof (UNS16), (void*)&OD_0_0_trashvariables_TRASH16 },
                       { RW, uint32, sizeof (UNS32), (void*)&OD_0_0_trashvariables_TRASH32 },
                       { RW, uint64, sizeof (UNS64), (void*)&OD_0_0_trashvariables_TRASH64 }
                     };

/* index 0x2208 :   Mapped variable beremiz__IB0_0_8 */
                    UNS8 OD_0_0_highestSubIndex_obj2208 = 1; /* number of subindex - 1*/
                    subindex OD_0_0_Index2208[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj2208 },
                       { RW, uint8, sizeof (UNS8), (void*)&beremiz__IB0_0_8_24576_1 }
                     };

/* index 0x4000 :   Mapped variable Can Bitrate */
                    subindex OD_0_0_Index4000[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Can_Bitrate }
                     };

/* index 0x4001 :   Mapped variable SYS_TICK_PERIOD_MS */
                    subindex OD_0_0_Index4001[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&SYS_TICK_PERIOD_MS }
                     };

/* index 0x4002 :   Mapped variable Axis Number */
                    subindex OD_0_0_Index4002[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Axis_Number }
                     };

/* index 0x4003 :   Mapped variable Axis Types */
                    UNS8 OD_0_0_highestSubIndex_obj4003 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4003[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4003 },
                       { RW, uint8, sizeof (UNS8), (void*)&Axis_Types[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&Axis_Types[1] },
                       { RW, uint8, sizeof (UNS8), (void*)&Axis_Types[2] },
                       { RW, uint8, sizeof (UNS8), (void*)&Axis_Types[3] }
                     };

/* index 0x4004 :   Mapped variable Axis Mods */
                    UNS8 OD_0_0_highestSubIndex_obj4004 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4004[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4004 },
                       { RW, uint8, sizeof (UNS8), (void*)&Axis_Mods[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&Axis_Mods[1] },
                       { RW, uint8, sizeof (UNS8), (void*)&Axis_Mods[2] },
                       { RW, uint8, sizeof (UNS8), (void*)&Axis_Mods[3] }
                     };

/* index 0x4005 :   Mapped variable Homing methods */
                    UNS8 OD_0_0_highestSubIndex_obj4005 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4005[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4005 },
                       { RW, int8, sizeof (INTEGER8), (void*)&Homing_methods[0] },
                       { RW, int8, sizeof (INTEGER8), (void*)&Homing_methods[1] },
                       { RW, int8, sizeof (INTEGER8), (void*)&Homing_methods[2] },
                       { RW, int8, sizeof (INTEGER8), (void*)&Homing_methods[3] }
                     };

/* index 0x4006 :   Mapped variable Homing Speeds during search for switch */
                    UNS8 OD_0_0_highestSubIndex_obj4006 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4006[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4006 },
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_Speeds_during_search_for_switch[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_Speeds_during_search_for_switch[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_Speeds_during_search_for_switch[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_Speeds_during_search_for_switch[3] }
                     };

/* index 0x4007 :   Mapped variable Homing Speeds during search for zero */
                    UNS8 OD_0_0_highestSubIndex_obj4007 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4007[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4007 },
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_Speeds_during_search_for_zero[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_Speeds_during_search_for_zero[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_Speeds_during_search_for_zero[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_Speeds_during_search_for_zero[3] }
                     };

/* index 0x4008 :   Mapped variable Homing Accelerations */
                    UNS8 OD_0_0_highestSubIndex_obj4008 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4008[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4008 },
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_Accelerations[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_Accelerations[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_Accelerations[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_Accelerations[3] }
                     };

/* index 0x4009 :   Mapped variable Homing Position offset */
                    UNS8 OD_0_0_highestSubIndex_obj4009 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4009[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4009 },
                       { RW, int32, sizeof (INTEGER32), (void*)&Homing_Position_offset[0] },
                       { RW, int32, sizeof (INTEGER32), (void*)&Homing_Position_offset[1] },
                       { RW, int32, sizeof (INTEGER32), (void*)&Homing_Position_offset[2] },
                       { RW, int32, sizeof (INTEGER32), (void*)&Homing_Position_offset[3] }
                     };

/* index 0x400A :   Mapped variable CAM 0 */
                    UNS8 OD_0_0_highestSubIndex_obj400A = 10; /* number of subindex - 1*/
                    subindex OD_0_0_Index400A[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj400A },
                       { RW, uint8, sizeof (UNS8), (void*)&CAM_0[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&CAM_0[1] },
                       { RW, uint8, sizeof (UNS8), (void*)&CAM_0[2] },
                       { RW, uint8, sizeof (UNS8), (void*)&CAM_0[3] },
                       { RW, uint8, sizeof (UNS8), (void*)&CAM_0[4] },
                       { RW, uint8, sizeof (UNS8), (void*)&CAM_0[5] },
                       { RW, uint8, sizeof (UNS8), (void*)&CAM_0[6] },
                       { RW, uint8, sizeof (UNS8), (void*)&CAM_0[7] },
                       { RW, uint8, sizeof (UNS8), (void*)&CAM_0[8] },
                       { RW, uint8, sizeof (UNS8), (void*)&CAM_0[9] }
                     };

/* index 0x400B :   Mapped variable CAM 1 */
                    UNS8 OD_0_0_highestSubIndex_obj400B = 10; /* number of subindex - 1*/
                    subindex OD_0_0_Index400B[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj400B },
                       { RW, uint8, sizeof (UNS8), (void*)&CAM_1[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&CAM_1[1] },
                       { RW, uint8, sizeof (UNS8), (void*)&CAM_1[2] },
                       { RW, uint8, sizeof (UNS8), (void*)&CAM_1[3] },
                       { RW, uint8, sizeof (UNS8), (void*)&CAM_1[4] },
                       { RW, uint8, sizeof (UNS8), (void*)&CAM_1[5] },
                       { RW, uint8, sizeof (UNS8), (void*)&CAM_1[6] },
                       { RW, uint8, sizeof (UNS8), (void*)&CAM_1[7] },
                       { RW, uint8, sizeof (UNS8), (void*)&CAM_1[8] },
                       { RW, uint8, sizeof (UNS8), (void*)&CAM_1[9] }
                     };

/* index 0x4010 :   Mapped variable Interpolation data records low */
                    UNS8 OD_0_0_highestSubIndex_obj4010 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4010[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4010 },
                       { RW, uint16, sizeof (UNS16), (void*)&Interpolation_data_records_low[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&Interpolation_data_records_low[1] },
                       { RW, uint16, sizeof (UNS16), (void*)&Interpolation_data_records_low[2] },
                       { RW, uint16, sizeof (UNS16), (void*)&Interpolation_data_records_low[3] }
                     };

/* index 0x4011 :   Mapped variable Interpolation data records high */
                    UNS8 OD_0_0_highestSubIndex_obj4011 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4011[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4011 },
                       { RW, uint16, sizeof (UNS16), (void*)&Interpolation_data_records_high[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&Interpolation_data_records_high[1] },
                       { RW, uint16, sizeof (UNS16), (void*)&Interpolation_data_records_high[2] },
                       { RW, uint16, sizeof (UNS16), (void*)&Interpolation_data_records_high[3] }
                     };

/* index 0x4012 :   Mapped variable ControlWords */
                    UNS8 OD_0_0_highestSubIndex_obj4012 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4012[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4012 },
                       { RW, uint16, sizeof (UNS16), (void*)&ControlWords[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&ControlWords[1] },
                       { RW, uint16, sizeof (UNS16), (void*)&ControlWords[2] },
                       { RW, uint16, sizeof (UNS16), (void*)&ControlWords[3] }
                     };

/* index 0x4020 :   Mapped variable Max accelerations */
                    UNS8 OD_0_0_highestSubIndex_obj4020 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4020[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4020 },
                       { RW, uint32, sizeof (UNS32), (void*)&Max_accelerations[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Max_accelerations[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Max_accelerations[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Max_accelerations[3] }
                     };

/* index 0x4021 :   Mapped variable Max Decelerations */
                    UNS8 OD_0_0_highestSubIndex_obj4021 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4021[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4021 },
                       { RW, uint32, sizeof (UNS32), (void*)&Max_Decelerations[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Max_Decelerations[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Max_Decelerations[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Max_Decelerations[3] }
                     };

/* index 0x4022 :   Mapped variable Max Velocitys */
                    UNS8 OD_0_0_highestSubIndex_obj4022 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4022[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4022 },
                       { RW, uint32, sizeof (UNS32), (void*)&Max_Velocitys[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Max_Velocitys[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Max_Velocitys[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Max_Velocitys[3] }
                     };

/* index 0x4030 :   Mapped variable Position Factor  Numerators */
                    UNS8 OD_0_0_highestSubIndex_obj4030 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4030[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4030 },
                       { RW, uint32, sizeof (UNS32), (void*)&Position_Factor_Numerators[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Position_Factor_Numerators[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Position_Factor_Numerators[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Position_Factor_Numerators[3] }
                     };

/* index 0x4031 :   Mapped variable Position Factor Feed Constants */
                    UNS8 OD_0_0_highestSubIndex_obj4031 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4031[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4031 },
                       { RW, uint32, sizeof (UNS32), (void*)&Position_Factor_Feed_Constants[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Position_Factor_Feed_Constants[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Position_Factor_Feed_Constants[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Position_Factor_Feed_Constants[3] }
                     };

/* index 0x4032 :   Mapped variable Pulse Per Rotate */
                    UNS8 OD_0_0_highestSubIndex_obj4032 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4032[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4032 },
                       { RW, uint32, sizeof (UNS32), (void*)&Pulse_Per_Rotate[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Pulse_Per_Rotate[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Pulse_Per_Rotate[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Pulse_Per_Rotate[3] }
                     };

/* index 0x4033 :   Mapped variable interrupt register */
                    UNS8 OD_0_0_highestSubIndex_obj4033 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4033[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4033 },
                       { RW, uint32, sizeof (UNS32), (void*)&interrupt_register[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&interrupt_register[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&interrupt_register[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&interrupt_register[3] }
                     };

/* index 0x4034 :   Mapped variable finish flag register */
                    UNS8 OD_0_0_highestSubIndex_obj4034 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4034[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4034 },
                       { RW, uint8, sizeof (UNS8), (void*)&finish_flag_register[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&finish_flag_register[1] },
                       { RW, uint8, sizeof (UNS8), (void*)&finish_flag_register[2] },
                       { RW, uint8, sizeof (UNS8), (void*)&finish_flag_register[3] }
                     };

/* index 0x4035 :   Mapped variable Execute flag register */
                    UNS8 OD_0_0_highestSubIndex_obj4035 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4035[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4035 },
                       { RW, uint8, sizeof (UNS8), (void*)&Execute_flag_register[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&Execute_flag_register[1] },
                       { RW, uint8, sizeof (UNS8), (void*)&Execute_flag_register[2] },
                       { RW, uint8, sizeof (UNS8), (void*)&Execute_flag_register[3] }
                     };

/* index 0x4036 :   Mapped variable command to request type */
                    UNS8 OD_0_0_highestSubIndex_obj4036 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4036[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4036 },
                       { RW, uint8, sizeof (UNS8), (void*)&command_to_request_type[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&command_to_request_type[1] },
                       { RW, uint8, sizeof (UNS8), (void*)&command_to_request_type[2] },
                       { RW, uint8, sizeof (UNS8), (void*)&command_to_request_type[3] }
                     };

/* index 0x4037 :   Mapped variable Pulse Equivalent */
                    UNS8 OD_0_0_highestSubIndex_obj4037 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4037[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4037 },
                       { RW, real32, sizeof (REAL32), (void*)&Pulse_Equivalent[0] },
                       { RW, real32, sizeof (REAL32), (void*)&Pulse_Equivalent[1] },
                       { RW, real32, sizeof (REAL32), (void*)&Pulse_Equivalent[2] },
                       { RW, real32, sizeof (REAL32), (void*)&Pulse_Equivalent[3] }
                     };

/* index 0x4040 :   Mapped variable Soft Limits Low */
                    UNS8 OD_0_0_highestSubIndex_obj4040 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4040[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4040 },
                       { RW, uint32, sizeof (UNS32), (void*)&Soft_Limits_Low[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Soft_Limits_Low[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Soft_Limits_Low[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Soft_Limits_Low[3] }
                     };

/* index 0x4041 :   Mapped variable Soft Limits High */
                    UNS8 OD_0_0_highestSubIndex_obj4041 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4041[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4041 },
                       { RW, uint32, sizeof (UNS32), (void*)&Soft_Limits_High[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Soft_Limits_High[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Soft_Limits_High[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Soft_Limits_High[3] }
                     };

/* index 0x4050 :   Mapped variable Gear Inputs */
                    UNS8 OD_0_0_highestSubIndex_obj4050 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4050[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4050 },
                       { RW, uint8, sizeof (UNS8), (void*)&Gear_Inputs[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&Gear_Inputs[1] },
                       { RW, uint8, sizeof (UNS8), (void*)&Gear_Inputs[2] },
                       { RW, uint8, sizeof (UNS8), (void*)&Gear_Inputs[3] }
                     };

/* index 0x4051 :   Mapped variable Gear Outputs */
                    UNS8 OD_0_0_highestSubIndex_obj4051 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4051[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4051 },
                       { RW, uint8, sizeof (UNS8), (void*)&Gear_Outputs[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&Gear_Outputs[1] },
                       { RW, uint8, sizeof (UNS8), (void*)&Gear_Outputs[2] },
                       { RW, uint8, sizeof (UNS8), (void*)&Gear_Outputs[3] }
                     };

/* index 0x4053 :   Mapped variable Gear Leads */
                    UNS8 OD_0_0_highestSubIndex_obj4053 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4053[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4053 },
                       { RW, uint32, sizeof (UNS32), (void*)&Gear_Leads[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Gear_Leads[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Gear_Leads[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Gear_Leads[3] }
                     };

/* index 0x4100 :   Mapped variable Modbus Bitrate */
                    subindex OD_0_0_Index4100[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Modbus_Bitrate }
                     };

/* index 0x4101 :   Mapped variable Modbus RTU or ASCII */
                    subindex OD_0_0_Index4101[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Modbus_RTU_or_ASCII }
                     };

/* index 0x4102 :   Mapped variable Modbus Slave Id */
                    subindex OD_0_0_Index4102[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Modbus_Slave_Id }
                     };

/* index 0x4103 :   Mapped variable Modbus Parity */
                    subindex OD_0_0_Index4103[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Modbus_Parity }
                     };

/* index 0x4110 :   Mapped variable Modbus Coils */
                    UNS16 OD_0_0_highestSubIndex_obj4110 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4110[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&OD_0_0_highestSubIndex_obj4110 },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Coils[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Coils[1] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Coils[2] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Coils[3] }
                     };

/* index 0x4111 :   Mapped variable Modbus Holdings */
                    UNS16 OD_0_0_highestSubIndex_obj4111 = 100; /* number of subindex - 1*/
                    subindex OD_0_0_Index4111[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&OD_0_0_highestSubIndex_obj4111 },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[1] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[2] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[3] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[4] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[5] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[6] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[7] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[8] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[9] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[10] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[11] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[12] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[13] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[14] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[15] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[16] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[17] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[18] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[19] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[20] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[21] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[22] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[23] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[24] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[25] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[26] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[27] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[28] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[29] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[30] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[31] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[32] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[33] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[34] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[35] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[36] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[37] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[38] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[39] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[40] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[41] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[42] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[43] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[44] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[45] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[46] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[47] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[48] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[49] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[50] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[51] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[52] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[53] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[54] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[55] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[56] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[57] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[58] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[59] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[60] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[61] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[62] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[63] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[64] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[65] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[66] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[67] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[68] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[69] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[70] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[71] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[72] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[73] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[74] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[75] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[76] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[77] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[78] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[79] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[80] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[81] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[82] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[83] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[84] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[85] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[86] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[87] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[88] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[89] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[90] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[91] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[92] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[93] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[94] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[95] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[96] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[97] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[98] },
                       { RW, uint16, sizeof (UNS16), (void*)&Modbus_Holdings[99] }
                     };

/* index 0x4120 :   Mapped variable Debug COM Port Birtrate */
                    subindex OD_0_0_Index4120[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Debug_COM_Port_Birtrate }
                     };

/* index 0x4200 :   Mapped variable Leds */
                    UNS8 OD_0_0_highestSubIndex_obj4200 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4200 },
                       { RW, uint8, sizeof (UNS8), (void*)&Leds[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&Leds[1] },
                       { RW, uint8, sizeof (UNS8), (void*)&Leds[2] },
                       { RW, uint8, sizeof (UNS8), (void*)&Leds[3] }
                     };

/* index 0x4201 :   Mapped variable Keys */
                    UNS8 OD_0_0_highestSubIndex_obj4201 = 4; /* number of subindex - 1*/
                    subindex OD_0_0_Index4201[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4201 },
                       { RW, uint8, sizeof (UNS8), (void*)&Keys[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&Keys[1] },
                       { RW, uint8, sizeof (UNS8), (void*)&Keys[2] },
                       { RW, uint8, sizeof (UNS8), (void*)&Keys[3] }
                     };

/* index 0x4208 :   Mapped variable beremiz__QB0_0_8 */
                    UNS8 OD_0_0_highestSubIndex_obj4208 = 1; /* number of subindex - 1*/
                    subindex OD_0_0_Index4208[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_0_0_highestSubIndex_obj4208 },
                       { RW, uint8, sizeof (UNS8), (void*)&beremiz__QB0_0_8_25088_1 }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/
UNS8* __IB0_0_8_24576_1 = &beremiz__IB0_0_8_24576_1;
UNS8* __QB0_0_8_25088_1 = &beremiz__QB0_0_8_25088_1;

const indextable OD_0_0_objdict[] = 
{
  { (subindex*)OD_0_0_Index1000,sizeof(OD_0_0_Index1000)/sizeof(OD_0_0_Index1000[0]), 0x1000},
  { (subindex*)OD_0_0_Index1001,sizeof(OD_0_0_Index1001)/sizeof(OD_0_0_Index1001[0]), 0x1001},
  { (subindex*)OD_0_0_Index1018,sizeof(OD_0_0_Index1018)/sizeof(OD_0_0_Index1018[0]), 0x1018},
  { (subindex*)OD_0_0_Index1280,sizeof(OD_0_0_Index1280)/sizeof(OD_0_0_Index1280[0]), 0x1280},
  { (subindex*)OD_0_0_Index1400,sizeof(OD_0_0_Index1400)/sizeof(OD_0_0_Index1400[0]), 0x1400},
  { (subindex*)OD_0_0_Index1600,sizeof(OD_0_0_Index1600)/sizeof(OD_0_0_Index1600[0]), 0x1600},
  { (subindex*)OD_0_0_Index1800,sizeof(OD_0_0_Index1800)/sizeof(OD_0_0_Index1800[0]), 0x1800},
  { (subindex*)OD_0_0_Index1A00,sizeof(OD_0_0_Index1A00)/sizeof(OD_0_0_Index1A00[0]), 0x1A00},
  { (subindex*)OD_0_0_Index1F22,sizeof(OD_0_0_Index1F22)/sizeof(OD_0_0_Index1F22[0]), 0x1F22},
  { (subindex*)OD_0_0_Index2000,sizeof(OD_0_0_Index2000)/sizeof(OD_0_0_Index2000[0]), 0x2000},
  { (subindex*)OD_0_0_Index2208,sizeof(OD_0_0_Index2208)/sizeof(OD_0_0_Index2208[0]), 0x2208},
  { (subindex*)OD_0_0_Index4000,sizeof(OD_0_0_Index4000)/sizeof(OD_0_0_Index4000[0]), 0x4000},
  { (subindex*)OD_0_0_Index4001,sizeof(OD_0_0_Index4001)/sizeof(OD_0_0_Index4001[0]), 0x4001},
  { (subindex*)OD_0_0_Index4002,sizeof(OD_0_0_Index4002)/sizeof(OD_0_0_Index4002[0]), 0x4002},
  { (subindex*)OD_0_0_Index4003,sizeof(OD_0_0_Index4003)/sizeof(OD_0_0_Index4003[0]), 0x4003},
  { (subindex*)OD_0_0_Index4004,sizeof(OD_0_0_Index4004)/sizeof(OD_0_0_Index4004[0]), 0x4004},
  { (subindex*)OD_0_0_Index4005,sizeof(OD_0_0_Index4005)/sizeof(OD_0_0_Index4005[0]), 0x4005},
  { (subindex*)OD_0_0_Index4006,sizeof(OD_0_0_Index4006)/sizeof(OD_0_0_Index4006[0]), 0x4006},
  { (subindex*)OD_0_0_Index4007,sizeof(OD_0_0_Index4007)/sizeof(OD_0_0_Index4007[0]), 0x4007},
  { (subindex*)OD_0_0_Index4008,sizeof(OD_0_0_Index4008)/sizeof(OD_0_0_Index4008[0]), 0x4008},
  { (subindex*)OD_0_0_Index4009,sizeof(OD_0_0_Index4009)/sizeof(OD_0_0_Index4009[0]), 0x4009},
  { (subindex*)OD_0_0_Index400A,sizeof(OD_0_0_Index400A)/sizeof(OD_0_0_Index400A[0]), 0x400A},
  { (subindex*)OD_0_0_Index400B,sizeof(OD_0_0_Index400B)/sizeof(OD_0_0_Index400B[0]), 0x400B},
  { (subindex*)OD_0_0_Index4010,sizeof(OD_0_0_Index4010)/sizeof(OD_0_0_Index4010[0]), 0x4010},
  { (subindex*)OD_0_0_Index4011,sizeof(OD_0_0_Index4011)/sizeof(OD_0_0_Index4011[0]), 0x4011},
  { (subindex*)OD_0_0_Index4012,sizeof(OD_0_0_Index4012)/sizeof(OD_0_0_Index4012[0]), 0x4012},
  { (subindex*)OD_0_0_Index4020,sizeof(OD_0_0_Index4020)/sizeof(OD_0_0_Index4020[0]), 0x4020},
  { (subindex*)OD_0_0_Index4021,sizeof(OD_0_0_Index4021)/sizeof(OD_0_0_Index4021[0]), 0x4021},
  { (subindex*)OD_0_0_Index4022,sizeof(OD_0_0_Index4022)/sizeof(OD_0_0_Index4022[0]), 0x4022},
  { (subindex*)OD_0_0_Index4030,sizeof(OD_0_0_Index4030)/sizeof(OD_0_0_Index4030[0]), 0x4030},
  { (subindex*)OD_0_0_Index4031,sizeof(OD_0_0_Index4031)/sizeof(OD_0_0_Index4031[0]), 0x4031},
  { (subindex*)OD_0_0_Index4032,sizeof(OD_0_0_Index4032)/sizeof(OD_0_0_Index4032[0]), 0x4032},
  { (subindex*)OD_0_0_Index4033,sizeof(OD_0_0_Index4033)/sizeof(OD_0_0_Index4033[0]), 0x4033},
  { (subindex*)OD_0_0_Index4034,sizeof(OD_0_0_Index4034)/sizeof(OD_0_0_Index4034[0]), 0x4034},
  { (subindex*)OD_0_0_Index4035,sizeof(OD_0_0_Index4035)/sizeof(OD_0_0_Index4035[0]), 0x4035},
  { (subindex*)OD_0_0_Index4036,sizeof(OD_0_0_Index4036)/sizeof(OD_0_0_Index4036[0]), 0x4036},
  { (subindex*)OD_0_0_Index4037,sizeof(OD_0_0_Index4037)/sizeof(OD_0_0_Index4037[0]), 0x4037},
  { (subindex*)OD_0_0_Index4040,sizeof(OD_0_0_Index4040)/sizeof(OD_0_0_Index4040[0]), 0x4040},
  { (subindex*)OD_0_0_Index4041,sizeof(OD_0_0_Index4041)/sizeof(OD_0_0_Index4041[0]), 0x4041},
  { (subindex*)OD_0_0_Index4050,sizeof(OD_0_0_Index4050)/sizeof(OD_0_0_Index4050[0]), 0x4050},
  { (subindex*)OD_0_0_Index4051,sizeof(OD_0_0_Index4051)/sizeof(OD_0_0_Index4051[0]), 0x4051},
  { (subindex*)OD_0_0_Index4053,sizeof(OD_0_0_Index4053)/sizeof(OD_0_0_Index4053[0]), 0x4053},
  { (subindex*)OD_0_0_Index4100,sizeof(OD_0_0_Index4100)/sizeof(OD_0_0_Index4100[0]), 0x4100},
  { (subindex*)OD_0_0_Index4101,sizeof(OD_0_0_Index4101)/sizeof(OD_0_0_Index4101[0]), 0x4101},
  { (subindex*)OD_0_0_Index4102,sizeof(OD_0_0_Index4102)/sizeof(OD_0_0_Index4102[0]), 0x4102},
  { (subindex*)OD_0_0_Index4103,sizeof(OD_0_0_Index4103)/sizeof(OD_0_0_Index4103[0]), 0x4103},
  { (subindex*)OD_0_0_Index4110,sizeof(OD_0_0_Index4110)/sizeof(OD_0_0_Index4110[0]), 0x4110},
  { (subindex*)OD_0_0_Index4111,sizeof(OD_0_0_Index4111)/sizeof(OD_0_0_Index4111[0]), 0x4111},
  { (subindex*)OD_0_0_Index4120,sizeof(OD_0_0_Index4120)/sizeof(OD_0_0_Index4120[0]), 0x4120},
  { (subindex*)OD_0_0_Index4200,sizeof(OD_0_0_Index4200)/sizeof(OD_0_0_Index4200[0]), 0x4200},
  { (subindex*)OD_0_0_Index4201,sizeof(OD_0_0_Index4201)/sizeof(OD_0_0_Index4201[0]), 0x4201},
  { (subindex*)OD_0_0_Index4208,sizeof(OD_0_0_Index4208)/sizeof(OD_0_0_Index4208[0]), 0x4208},
};

const indextable * OD_0_0_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1018: i = 2;break;
		case 0x1280: i = 3;break;
		case 0x1400: i = 4;break;
		case 0x1600: i = 5;break;
		case 0x1800: i = 6;*callbacks = OD_0_0_Index1800_callbacks; break;
		case 0x1A00: i = 7;break;
		case 0x1F22: i = 8;break;
		case 0x2000: i = 9;break;
		case 0x2208: i = 10;break;
		case 0x4000: i = 11;break;
		case 0x4001: i = 12;break;
		case 0x4002: i = 13;break;
		case 0x4003: i = 14;break;
		case 0x4004: i = 15;break;
		case 0x4005: i = 16;break;
		case 0x4006: i = 17;break;
		case 0x4007: i = 18;break;
		case 0x4008: i = 19;break;
		case 0x4009: i = 20;break;
		case 0x400A: i = 21;break;
		case 0x400B: i = 22;break;
		case 0x4010: i = 23;break;
		case 0x4011: i = 24;break;
		case 0x4012: i = 25;break;
		case 0x4020: i = 26;break;
		case 0x4021: i = 27;break;
		case 0x4022: i = 28;break;
		case 0x4030: i = 29;break;
		case 0x4031: i = 30;break;
		case 0x4032: i = 31;break;
		case 0x4033: i = 32;break;
		case 0x4034: i = 33;break;
		case 0x4035: i = 34;break;
		case 0x4036: i = 35;break;
		case 0x4037: i = 36;break;
		case 0x4040: i = 37;break;
		case 0x4041: i = 38;break;
		case 0x4050: i = 39;break;
		case 0x4051: i = 40;break;
		case 0x4053: i = 41;break;
		case 0x4100: i = 42;break;
		case 0x4101: i = 43;break;
		case 0x4102: i = 44;break;
		case 0x4103: i = 45;break;
		case 0x4110: i = 46;break;
		case 0x4111: i = 47;break;
		case 0x4120: i = 48;break;
		case 0x4200: i = 49;break;
		case 0x4201: i = 50;break;
		case 0x4208: i = 51;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &OD_0_0_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status OD_0_0_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index OD_0_0_firstIndex = {
  0, /* SDO_SVR */
  3, /* SDO_CLT */
  4, /* PDO_RCV */
  5, /* PDO_RCV_MAP */
  6, /* PDO_TRS */
  7 /* PDO_TRS_MAP */
};

const quick_index OD_0_0_lastIndex = {
  0, /* SDO_SVR */
  3, /* SDO_CLT */
  4, /* PDO_RCV */
  5, /* PDO_RCV_MAP */
  6, /* PDO_TRS */
  7 /* PDO_TRS_MAP */
};

const UNS16 OD_0_0_ObjdictSize = sizeof(OD_0_0_objdict)/sizeof(OD_0_0_objdict[0]); 

CO_Data OD_0_0_Data = CANOPEN_NODE_DATA_INITIALIZER(OD_0_0);

